### ISSUE TITLE
[Suggestion] Ignore Pawns with "incapable of violence" traits

### ISSUE THREAD

**Issue by frenchiveruti** [KiameV/rimworld-weaponstorage#1]
Right now and for small colonies, the mod is fine, the GUI is kinda big but I understand that you are in any way a designer, but you are a great programmer!
So my suggestion is to at least reduce the clutter that gets generated by a large amount of colonist ignoring pawns incapable of violence as they are completely incapable of carrying guns.  
Even more, I'm afraid to even assign them a weapon and crashing the game ha.

**Comment by KiameV** [comment]
Done with latest update
