### ISSUE TITLE
Check game state before executing scribe prefix

### ISSUE THREAD

**Issue by FluffierThanThou** [KiameV/rimworld-weaponstorage#3]
In https://github.com/KiameV/rimworld-weaponstorage/blob/master/Source/HarmonyPatches.cs#L537 you're running a prefix on `ScribeSaver.InitSaving`. This prefix fails when the `WeaponStoragesToUse` list in `WorldComp` is populated, but the map for these storages is `null`. My guess is after closing a game and returning to the main menu, the `WeaponStoragesToUse` list is not cleared. That's causing some issues in other scribe calls, and a potential memory leak. 

Please either;

- clear the list of weapon storages to use when quitting the current game,
- check if in a game before executing the prefix

**Comment by FluffierThanThou** [comment]
https://pastebin.com/LWUQ3e5k

**Comment by KiameV** [comment]
Thanks. Added code to help prevent this.
