### ISSUE TITLE
Colonists drop weapons randomly after undrafted

### ISSUE THREAD

**Issue by dat-ho** [KiameV/rimworld-weaponstorage#6]
I am not sure why. There is no error in Dev log but when I draft my colonists, they did not equip assigned weapons but I have to click on the Equip weapon icons. When I undraft them, they drop the equipped weapons and those weapons become Unassigned. I have to Reassign them again. Also when they are assigned with weapons by using Weapon Storage, they still do not use assigned weapons to attack, for example: when Animal Revenge, they just use fist to beat the animal instead of using the assigned knife.

I do not think these are correct behaviors of Weapon Storage. Never happen before.

Hope you can look into those issues and the error with Reload turrets. Thanks

**Comment by dat-ho** [comment]
I just find out that Drop assigned weapons on Undrafted only happens when we use CE Loadouts, even the loadouts have no weapons just Medicines and Meals.

And to fix this issue, we have to assign colonists with the CE Loadout that has the same weapons that we assigned to them through Weapon Storage

**Comment by KiameV** [comment]
CE was/is not supported by this mod.
