### ISSUE TITLE
Can't get ammo from weapon Storage

### ISSUE THREAD

**Issue by Darktotaled** [KiameV/rimworld-weaponstorage#9]
Basically what is happening is that i need to drop all the ammo on the ground from the storage to be able to interact with it. Im assuming its not the intended way. What would be the mod order for Weapon Storage and CE, just so i can properly test it?
rimworld 1.2
115 mods
CE 1.2.3.8
WS 1.3.0.2

**Comment by KiameV** [comment]
I tried supporting CE but that mod changes too often and breaks compatibility constantly. I do not have time to keep up with it and for that reason I will not be supporting CE.

If someone would like to add support for CE all they need to do is create a PR and I'll include it.

**Comment by Darktotaled** [comment]
Oh ok. Thanks for your time tho man. I appreciate
